/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.almasoft.almagest.view.clientes;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amdel
 */
public class ClientesPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientesPanel
     */
    private static ClientesPanel instanciaClientesPanel;
    private DefaultTableModel modelo;

    public ClientesPanel() {
        initComponents();
        this.modelo = (DefaultTableModel) this.jTableClientes.getModel();
        add(new JScrollPane(jTableClientes), BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneClientes = new javax.swing.JTabbedPane();
        jPanelListaClientes = new javax.swing.JPanel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanelDatosPersonales = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimientos de Clientes");

        jPanelListaClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Clientes"));
        jPanelListaClientes.setLayout(new java.awt.BorderLayout());

        jTableClientes.setAutoCreateRowSorter(true);
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Registro", "NIF", "Apellido paterno", "Apellido materno", "Nombre", "Fecha de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneClientes.setViewportView(jTableClientes);

        jPanelListaClientes.add(jScrollPaneClientes, java.awt.BorderLayout.CENTER);

        jTabbedPaneClientes.addTab("Lista de Clientes", jPanelListaClientes);

        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanelDatosPersonales.setLayout(new java.awt.BorderLayout());
        jTabbedPaneClientes.addTab("Datos Personales", jPanelDatosPersonales);

        getContentPane().add(jTabbedPaneClientes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelListaClientes;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JTabbedPane jTabbedPaneClientes;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables

    public static ClientesPanel getInstance() {
        if (instanciaClientesPanel == null) {
            instanciaClientesPanel = new ClientesPanel();
        }
        return instanciaClientesPanel;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }

    public JTable getjTableClientes() {
        return jTableClientes;
    }

    public void setjTableClientes(JTable jTableClientes) {
        this.jTableClientes = jTableClientes;
    }
    
    

}
