/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.almasoft.almagest.view.main;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.DesktopManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author amdel
 */
public class MainMDI extends javax.swing.JFrame {

    private PassWordDialog passDialog;

    /**
     * Constructor para la clase MainMDI
     */
    public MainMDI() {
        //Seteamos los valores de visualización Look And Fell

        

        //PassWordDialog pass = new PassWordDialog();
        //pass.setVisible(true);
        //Inicializamos componentes del frame
        initComponents();
        getContentPane().add(pane, BorderLayout.CENTER);

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        //passDialog = new PassWordDialog(this, true);
        //passDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTablasBasicas = new javax.swing.JMenu();
        jMenuMantClientes = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlmaGestión");

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(pane, java.awt.BorderLayout.CENTER);

        jMenuTablasBasicas.setLabel("Tablas Básicas");

        jMenuMantClientes.setText("Mantenimiento de Clientes");
        jMenuMantClientes.setActionCommand("MantClientes");
        jMenuTablasBasicas.add(jMenuMantClientes);

        jMenuBar1.add(jMenuTablasBasicas);

        jMenuAyuda.setText("Ayuda");
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(pane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMDI().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuMantClientes;
    private javax.swing.JMenu jMenuTablasBasicas;
    private javax.swing.JDesktopPane pane;
    // End of variables declaration//GEN-END:variables


    public JMenuItem getjMenuMantClientes() {
        return jMenuMantClientes;
    }

    public void setjMenuMantClientes(JMenuItem jMenuMantClientes) {
        this.jMenuMantClientes = jMenuMantClientes;
    }

    public JDesktopPane getPane() {
        return pane;
    }

    public void setPane(JDesktopPane pane) {
        this.pane = pane;
    }

}
